/pov:
  ros__parameters: 
    window_size: 10

/avg:
  ros__parameters: 
    front_angle: 90
    window_size: 180

/tracker:
  ros__parameters: 
    max_speed: 1.0
    max_distance: 5.0
    min_distance: 2.0
